remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

title: wittyphantom333
description: a personal architecture site

show_downloads: true
#google_analytics: [Your Google Analytics tracking ID]
